# Generated by Django 3.1.4 on 2020-12-05 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201205_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='tag',
        ),
    ]
