# Generated by Django 3.1.4 on 2020-12-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20201219_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.FileField(upload_to='new_image'),
        ),
    ]
