# Generated by Django 3.1.4 on 2020-12-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20201219_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.ImageField(upload_to='new_image'),
        ),
    ]
